- op: replace
  path: /Resources/TaskDefinition/Properties/RequiresCompatibilities/0
  value: EXTERNAL
- op: replace
  path: /Resources/TaskDefinition/Properties/NetworkMode
  value: bridge
- op: replace
  path: /Resources/Service/Properties/LaunchType
  value: EXTERNAL
- op: remove
  path: /Resources/Service/Properties/PlatformVersion
- op: remove
  path: /Resources/Service/Properties/NetworkConfiguration

- op: add
  path: /Resources/TaskDefinition/Properties/ContainerDefinitions/0/PortMappings
  value:
    - ContainerPort: 80
      HostPort: 80
      Protocol: tcp
    - ContainerPort: 8080
      HostPort: 8080
      Protocol: tcp

- op: add
  path: /Resources/TaskDefinition/Properties/Volumes/0/Host
  value: /var/run/docker.sock
