name: traefik
type: Backend Service

image:
  location: public.ecr.aws/docker/library/traefik:v3.0

cpu: 256
memory: 1024
count: 1
exec: true

deployment:
  # Traefik has binds to some ports on the host and because of that rolling updates have to be disabled
  rolling: recreate

command:
  - "--api.dashboard=true"
  - "--api.insecure=true"
  - "--accesslog=true"
  - "--providers.ecs.ecsAnywhere=true"
  - "--providers.ecs.region=eu-central-1"
  - "--providers.ecs.autoDiscoverClusters=true"
  - "--providers.ecs.exposedByDefault=false"
